import cn from "classnames";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../common/styles/globals.css";

import { Divider } from "@/components/common/Divider/Divider";
import { Header } from "@/components/layout/Header/Header";
import { QueryProvider } from "@/components/layout/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "text-black bg-white dark:text-white dark:bg-black",
        )}
      >
        <div className="py-[43px] px-[100px] gap-">
          <Header />
          <div className="mt-[42px] mb-[82px] w-full">
            <Divider />
          </div>
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
